# spring configuration
spring:
   application:
      name: myweb

   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp

# spring configuration
server:
   prot: 8088
   servlet:
      context-path: /
      encoding:
         charset: utf-8
         enabled: true